source 'https://rubygems.org'
gem 'github-pages', '>= 204'
gem 'nokogiri', '>= 1.11.4'
gem 'html5_validator'
gem 'w3c_validators', '>= 1.3.4'
gem 'colorize'
gem 'html-proofer', '>= 3.15.1'
gem 'open_uri_redirections'
