source 'https://rubygems.org'
gem 'github-pages', '>= 229'
gem 'nokogiri', '>= 1.18.8'
gem 'html5_validator'
gem 'w3c_validators', '>= 1.3.6'
gem 'colorize'
gem 'html-proofer', '>= 3.19.2'
gem 'open_uri_redirections'
